version: "3.9"
services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres_initial:
    image: postgres:16
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/postgres
      AUTH_USER: root
      AUTH_PASSWORD: root
    depends_on:
      - postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
