version: "3.9"

services:
  # ────────────────────────────
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base "vierge" pour tes migrations initiales (optionnelle)
  postgres_initial:
    image: postgres:16
    container_name: postgres_initial
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  # ────────────────────────────
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    ports:
      - "6432:6432"
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/postgres
      AUTH_USER: root
      AUTH_PASSWORD: root
    depends_on:
      - postgres

  # ────────────────────────────
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # ────────────────────────────
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    ports:
      - "5050:80" # http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: supersecret
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin # conserve tes favoris
      - ./pgadmin/servers.json:/pgadmin4/servers.json # ← Configuration des serveurs pgAdmin

    depends_on:
      - postgres
    # facultatif, mais pratique pour copier un servers.json pré-configuré :
    #  - ./pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
  pgadmin_data:
